version: "3"
services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: hepsiburada-backend
  client:
    build: ./frontend
    ports:
      - "3005:3000"
    stdin_open: true
    container_name: hepsiburada-frontend
    depends_on:
      - api